services:
  postgres:
    image: postgres
    container_name: has_core-backend_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: echostream_db
    ports:
      - "55110:5432"
    volumes:
      - postgres_data:/var/lib/has/postgresql/data/core-backend

  redis:
    image: redis
    container_name: has_core-backend_redis
    restart: always
    ports:
      - "55120:6379"

  influxdb:
    image: influxdb
    container_name: has_core-backend_influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: secret
      DOCKER_INFLUXDB_INIT_ORG: has_core-backend_org
      DOCKER_INFLUXDB_INIT_BUCKET: has_core-backend_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: has_core-backend_token
    ports:
      - "55130:8086"
    volumes:
      - influxdb_data:/var/lib/has/influxdb2/core-backend

volumes:
  postgres_data:
  influxdb_data:
