# Application configuration for EchoStream Backend
server:
  port: 55100  # Port for Spring Boot application

# PostgreSQL Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:55110/echostream_db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # Use 'validate' or 'none' in production
    show-sql: false # LOG
    open-in-view: false

# Redis Configuration
redis:
  host: localhost
  port: 55120

# InfluxDB Configuration
influx:
  url: http://localhost:55130
  token: has-backend_token
  bucket: has-backend_bucket
  org: has-backend_org

# APP
app_settings:
  api:
    base-url: http://localhost:55100/api
    log-detail: false

