services:
  postgres:
    image: postgres
    container_name: has_backend-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: echostream_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/has/postgresql/data

  redis:
    image: redis
    container_name: has_backend-redis
    restart: always
    ports:
      - "6379:6379"

  influxdb:
    image: influxdb
    container_name: has_backend-influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: secret
      DOCKER_INFLUXDB_INIT_ORG: has-backend_org
      DOCKER_INFLUXDB_INIT_BUCKET: has-backend_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: has-backend_token
    ports:
      - "8087:8086"
    volumes:
      - influxdb_data:/var/lib/has/influxdb2

volumes:
  postgres_data:
  influxdb_data:
